"""Claude Code formatter - generates CLAUDE.md file."""

from pathlib import Path
from typing import Any, Dict, List

# Handle both relative and absolute imports
try:
    from ..base import BaseFormatter, FormatterConfig, FormatterResult
except ImportError:
    from base import BaseFormatter, FormatterConfig, FormatterResult


class ClaudeFormatter(BaseFormatter):
    """Formatter for Claude Code (CLAUDE.md file)."""

    name = "Claude Code"
    tool_id = "claude"
    description = "Generates CLAUDE.md file for Claude Code"
    file_extension = ".md"
    supports_multiple_files = False

    def format_rules(
        self,
        compiled_rules: List[Dict[str, Any]],
        project_context: Dict[str, Any],
        output_dir: Path,
    ) -> FormatterResult:
        """
        Format rules as CLAUDE.md file.

        Creates:
        - CLAUDE.md (single comprehensive file)
        """
        output_path = self.get_output_path(output_dir / "CLAUDE.md")

        files_created: List[Path] = []
        files_updated: List[Path] = []
        errors: List[str] = []

        try:
            content = self._generate_content(compiled_rules, project_context)

            if output_path.exists():
                files_updated.append(output_path)
            else:
                files_created.append(output_path)

            output_path.write_text(content)

            return FormatterResult(
                success=True,
                files_created=files_created,
                files_updated=files_updated,
                errors=errors,
            )

        except Exception as e:
            return FormatterResult(
                success=False,
                files_created=files_created,
                files_updated=files_updated,
                errors=[str(e)],
            )

    def _generate_content(
        self,
        rules: List[Dict[str, Any]],
        context: Dict[str, Any],
    ) -> str:
        """Generate CLAUDE.md content."""

        # Sort rules: core first, then by weight
        sorted_rules = sorted(
            rules,
            key=lambda x: (
                0 if x.get("category") == "core" else 1,
                -x.get("weight", 50),
            ),
        )

        content = f"""# {context.get("project_name", "Project")} - AI Assistant Rules

## Project Overview

- **Technology Stack:** {context.get("selected_stack", "Not specified")}
- **Generated:** {context.get("timestamp", "Unknown")}
- **Mode:** {context.get("generation_mode", "quick")}

### About This Project

{context.get("project_description", "No description provided.")}

## Core Principles (Always Apply)

"""

        # Add always-apply rules first
        core_rules = [r for r in sorted_rules if r.get("alwaysApply")]
        for rule in core_rules:
            content += self._format_rule_section(rule)

        content += "\n## Stack-Specific Guidelines\n\n"

        # Add stack-specific rules
        stack_rules = [r for r in sorted_rules if r.get("category") == "stack"]
        for rule in stack_rules:
            content += self._format_rule_section(rule)

        content += "\n## Domain-Specific Patterns\n\n"

        # Add domain rules
        domain_rules = [r for r in sorted_rules if r.get("category") == "domain"]
        for rule in domain_rules:
            content += self._format_rule_section(rule)

        content += f"""
## Communication Preferences

Based on this project's configuration:

- **Team Size:** {context.get("team_size", "Unknown")}
- **Primary Constraint:** {context.get("priority_constraint", "Not specified")}
- **Documentation Level:** {context.get("documentation_level", "Not specified")}

### When to Ask vs Act

Ask when:
- Requirements are ambiguous
- Multiple valid architectural approaches exist
- Security implications are unclear

Act when:
- Following established patterns in the codebase
- Clear technical path forward
- Routine implementation tasks

## Additional Context

"""

        if context.get("additional_notes"):
            content += f"### Special Requirements\n\n{context['additional_notes']}\n\n"

        content += """### Resources

- Refer to individual source files for specific implementation patterns
- When uncertain, prefer explicit type annotations and error handling
- Security and data validation are always top priorities

---

*This file was generated by Rulesmith. Update it by running `rulesmith init` again.*
"""

        return content

    def _format_rule_section(self, rule: Dict[str, Any]) -> str:
        """Format a single rule as a section."""
        section = f"### {rule.get('id', 'Rule')}\n\n"
        section += f"**Applies to:** `{rule.get('globs', '*')}`\n\n"

        if rule.get("description"):
            section += f"{rule['description']}\n\n"

        # Add the rule content
        section += rule.get("content", "")
        section += "\n\n"

        return section

    def validate_output(self, output_path: Path) -> bool:
        """Validate CLAUDE.md exists and has required sections."""
        if not output_path.exists():
            return False

        content = output_path.read_text()

        # Must have key sections
        required_sections = [
            "Project Overview",
            "Core Principles",
            "Stack-Specific Guidelines",
        ]

        for section in required_sections:
            if section not in content:
                return False

        return True
