"""GitHub Copilot formatter - generates copilot-instructions.md."""

from pathlib import Path
from typing import Any, Dict, List

# Handle both relative and absolute imports
try:
    from ..base import BaseFormatter, FormatterConfig, FormatterResult
except ImportError:
    from base import BaseFormatter, FormatterConfig, FormatterResult


class CopilotFormatter(BaseFormatter):
    """Formatter for GitHub Copilot."""

    name = "GitHub Copilot"
    tool_id = "copilot"
    description = "Generates .github/copilot-instructions.md"
    file_extension = ".md"
    supports_multiple_files = False

    def format_rules(
        self,
        compiled_rules: List[Dict[str, Any]],
        project_context: Dict[str, Any],
        output_dir: Path,
    ) -> FormatterResult:
        """Generate copilot-instructions.md file."""
        output_path = self.get_output_path(
            output_dir / ".github" / "copilot-instructions.md"
        )
        self.prepare_output_dir(output_path.parent)

        files_created: List[Path] = []
        files_updated: List[Path] = []
        errors: List[str] = []

        try:
            content = self._generate_content(compiled_rules, project_context)

            if output_path.exists():
                files_updated.append(output_path)
            else:
                files_created.append(output_path)

            output_path.write_text(content)

            return FormatterResult(
                success=True,
                files_created=files_created,
                files_updated=files_updated,
                errors=errors,
            )

        except Exception as e:
            return FormatterResult(
                success=False,
                files_created=files_created,
                files_updated=files_updated,
                errors=[str(e)],
            )

    def _generate_content(
        self,
        rules: List[Dict[str, Any]],
        context: Dict[str, Any],
    ) -> str:
        """Generate copilot-instructions.md content."""

        content = f"""# GitHub Copilot Instructions

## Project Context

**Stack:** {context.get("selected_stack", "Not specified")}
**Framework:** {context.get("detected_stack", "Unknown")}

### Coding Standards

"""

        # Add high-weight rules
        high_weight_rules = [r for r in rules if r.get("weight", 50) >= 70]
        for rule in high_weight_rules:
            content += f"- {rule.get('description', rule.get('id'))}\n"

        content += """
## Pull Request Guidelines

"""

        # Add code review related content
        review_rules = [r for r in rules if "review" in r.get("id", "").lower()]
        for rule in review_rules:
            content += rule.get("content", "")
            content += "\n\n"

        content += f"""## Testing Approach

{context.get("testing_approach", "Write tests for new functionality")}

## Additional Notes

{context.get("additional_notes", "")}

---

*Generated by Rulesmith*
"""

        return content

    def validate_output(self, output_path: Path) -> bool:
        """Validate copilot-instructions.md exists."""
        return output_path.exists()
