"""Requirements document generator."""

from jinja2 import Template
from datetime import datetime
from typing import Dict, List, Any


REQUIREMENTS_TEMPLATE = """# Project Requirements Document

**Generated:** {{ timestamp }}  
**Project:** {{ project_name or "Unnamed Project" }}  
**Stack:** {{ detected_stack }}  

## Executive Summary

{{ project_description or "No description provided" }}

### Key Characteristics
- **Team Size:** {{ team_size or "Unknown" }}
- **Primary Constraint:** {{ priority_constraint or "Not specified" }}
- **Architecture:** {{ architecture_pattern or "Not specified" }}

## Technology Stack

**Primary Stack:** {{ detected_stack }}

{% if manual_stack and manual_stack != detected_stack %}
**User-Selected Stack:** {{ manual_stack }}
{% endif %}

## Development Practices

### Code Quality
- **Testing Approach:** {{ testing_approach or "Not specified" }}
- **Code Review:** {{ code_review or "Not specified" }}
- **Documentation:** {{ documentation_level or "Not specified" }}
- **Code Style:** {{ code_style or "Not specified" }}

{% if state_management %}
### State Management
- **State Management:** {{ state_management }}
{% endif %}

{% if api_style %}
- **API Style:** {{ api_style }}
{% endif %}

## Constraints & Priorities

{% if performance_critical %}
### Performance
- Performance is **critical** for this project
{% endif %}

{% if security_compliance and security_compliance != "None" %}
### Security & Compliance
- Required compliance: **{{ security_compliance }}**
{% endif %}

### Scalability
- Expected scale: {{ scalability_concerns or "Not specified" }}

## AI Assistant Configuration

### Target Tools
{% if target_tools %}
{% for tool in target_tools %}
- {{ tool }}
{% endfor %}
{% elif primary_ai_tool %}
- {{ primary_ai_tool }}
{% if secondary_tools %}
- Secondary: {% for tool in secondary_tools %}{{ tool }}{% if not loop.last %}, {% endif %}{% endfor %}
{% endif %}
{% else %}
_Not specified_
{% endif %}

### Experience Level
- Team experience: {{ ai_experience_level or "Not specified" }}

## Special Requirements

{% if additional_notes %}
{{ additional_notes }}
{% else %}
_No special requirements noted._
{% endif %}

## Rule Generation Summary

- **Mode:** {{ generation_mode }}
- **Total Rules Generated:** {{ total_rules }}
- **Core Rules:** {{ core_rules_count }}
- **Stack Rules:** {{ stack_rules_count }}
- **Domain Rules:** {{ domain_rules_count }}

---

*This document was automatically generated by Rulesmith.*
"""


class RequirementsGenerator:
    """Generates comprehensive requirements document."""

    def __init__(self):
        self.template = Template(REQUIREMENTS_TEMPLATE)

    def generate(
        self,
        interview_answers: Dict[str, Any],
        detected_stack: str,
        compiled_rules: List[Dict[str, Any]],
        generation_mode: str,
    ) -> str:
        """Generate requirements document."""
        # Count rule types
        core_rules = [r for r in compiled_rules if r.get("category") == "core"]
        stack_rules = [r for r in compiled_rules if r.get("category") == "stacks"]
        domain_rules = [r for r in compiled_rules if r.get("category") == "domain"]

        context = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "detected_stack": detected_stack,
            "generation_mode": generation_mode,
            "total_rules": len(compiled_rules),
            "core_rules_count": len(core_rules),
            "stack_rules_count": len(stack_rules),
            "domain_rules_count": len(domain_rules),
            **interview_answers,
        }

        return self.template.render(**context)
